server:
  port: 10000

spring:
  webflux:
    base-path: /api/v1
  application:
    name: scooz-tenant-api
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.regfb.mongodb.net?authSource=admin&replicaSet=atlas-a6o6iy-shard-0&readPreference=primary&appname=scooz-tenant-api&ssl=true
      database: scooz_tenant
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.discovery: OFF
  file: /tmp/logs/${spring.application.name}.log
