server:
  port: 10000

spring:
  webflux:
    base-path: /api/v1
  application:
    name: scooz-gateway-api
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.regfb.mongodb.net/?authSource=admin&replicaSet=atlas-a6o6iy-shard-0&readPreference=primary&appname=scooz-gateway-api&ssl=true
      database: scooz_authentication
      auto-index-creation: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.netflix.discovery: OFF
  file: /tmp/logs/${spring.application.name}.log

global:
  super:
    user: ${sper_user:super.user}
    pwd: ${super_pwd:super.user}
  jwt:
    exp: 3600
    secret: x72RAQeDEoRrOuvIPTaIxkmUNWgyr6x0
