server:
  port: 10000
  servlet:
    context-path: /api/v1

spring:
  application:
    name: scooz-auth-api
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.regfb.mongodb.net/scooz_authentication?authSource=admin&replicaSet=atlas-a6o6iy-shard-0&readPreference=primary&appname=scooz-auth-api&ssl=true
      database: scooz_authentication
      auto-index-creation: true
  boot:
    admin:
      client:
        url: http://localhost:8762
        username: admin
        password: adminPa33word

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  file: /tmp/logs/${spring.application.name}.log

jwt:
  exp: 3600
  secret: x72RAQeDEoRrOuvIPTaIxkmUNWgyr6x0
