server:
  port: 10000
  servlet:
    context-path: /api/v1

spring:
  application:
    name: scooz-auth-api
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.regfb.mongodb.net/scooz_authentication?authSource=admin&replicaSet=atlas-a6o6iy-shard-0&readPreference=primary&appname=scooz-auth-api&ssl=true
      database: scooz_authentication
      auto-index-creation: true

logging:
  file: /tmp/logs/${spring.application.name}.log

jwt:
  exp: 3600
  secret: x72RAQeDEoRrOuvIPTaIxkmUNWgyr6x0